const db=window.SCHOOL_SUPABASE,$=s=>document.querySelector(s);let rows=[],settings={};
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normalize=v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');const collator=new Intl.Collator('th',{numeric:true,sensitivity:'base'});
function placeholder(name=''){const initials=String(name).trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('')||'ศ';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="100%" height="100%" fill="#fff7ed"/><circle cx="200" cy="200" r="115" fill="#fed7aa"/><text x="200" y="225" font-family="sans-serif" text-anchor="middle" font-size="82" font-weight="700" fill="#c2410c">${initials}</text></svg>`)}
function pathReady(x){return !!(x.show_pathway && (x.further_study_institution||x.faculty||x.major||x.career_group));}
async function load(){lucide.createIcons();if(!db){renderError('ยังไม่ได้ตั้งค่า Supabase');return}const [a,s]=await Promise.all([db.from('alumni').select('id,full_name,photo_url,batch,further_study_institution,faculty,major,degree_level,study_start_year,study_end_year,career_group,current_position,occupation,organization,show_pathway').eq('published',true).order('batch',{ascending:true}),db.from('site_settings').select('data').eq('id',1).maybeSingle()]);if(a.error){renderError('กรุณารัน ALUMNI-PATHWAYS-SUPABASE.sql ก่อนใช้งาน');return}rows=(a.data||[]).filter(pathReady);settings=s.data?.data||{};applyBrand();buildFilters();render();}
function applyBrand(){const name=settings?.info?.nameTh||'โรงเรียนวัดหนองแวงวิทยา';$('#school-name').textContent=name;document.title=`เส้นทางศึกษาต่อศิษย์เก่า - ${name}`;const logo=settings?.branding?.logoUrl;if(logo){$('#school-logo').src=logo;$('#school-logo').classList.remove('hidden');$('#logo-fallback').classList.add('hidden')}}
function buildFilters(){const batches=[...new Set(rows.map(x=>x.batch).filter(Boolean))].sort((a,b)=>collator.compare(b,a));const institutions=[...new Set(rows.map(x=>x.further_study_institution).filter(Boolean))].sort(collator.compare);const careers=[...new Set(rows.map(x=>x.career_group).filter(Boolean))].sort(collator.compare);$('#batch-filter').innerHTML='<option value="">ทุกรุ่น</option>'+batches.map(x=>`<option>${esc(x)}</option>`).join('');$('#institution-filter').innerHTML='<option value="">ทุกสถาบัน</option>'+institutions.map(x=>`<option>${esc(x)}</option>`).join('');$('#career-filter').innerHTML='<option value="">ทุกกลุ่มอาชีพ</option>'+careers.map(x=>`<option>${esc(x)}</option>`).join('');$('#stat-people').textContent=rows.length.toLocaleString('th-TH');$('#stat-institutions').textContent=institutions.length.toLocaleString('th-TH');$('#stat-majors').textContent=new Set(rows.map(x=>x.major||x.faculty).filter(Boolean)).size.toLocaleString('th-TH');$('#stat-careers').textContent=careers.length.toLocaleString('th-TH')}
function filtered(){const q=normalize($('#search').value),b=$('#batch-filter').value,i=$('#institution-filter').value,c=$('#career-filter').value;return rows.filter(x=>{const hay=normalize([x.full_name,x.batch,x.further_study_institution,x.faculty,x.major,x.degree_level,x.current_position,x.occupation,x.organization,x.career_group].join(' '));return(!q||hay.includes(q))&&(!b||x.batch===b)&&(!i||x.further_study_institution===i)&&(!c||x.career_group===c)})}
function counts(arr,keyFn){const m=new Map();arr.forEach(x=>{const k=keyFn(x)||'ไม่ระบุ';m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]||collator.compare(a[0],b[0]));}
function node(title,subtitle,icon,accent='orange'){const map={orange:'bg-orange-50 text-orange-700 border-orange-100',amber:'bg-amber-50 text-amber-700 border-amber-100',slate:'bg-slate-50 text-slate-700 border-slate-200',emerald:'bg-emerald-50 text-emerald-700 border-emerald-100'};return `<div class="flow-node glass rounded-[1.7rem] p-5 min-h-32 flex items-center gap-4"><div class="w-11 h-11 rounded-2xl ${map[accent]} border flex items-center justify-center shrink-0"><i data-lucide="${icon}" class="w-5 h-5"></i></div><div class="min-w-0"><p class="font-black text-slate-900 leading-snug">${esc(title)}</p><p class="text-xs text-slate-500 mt-1">${esc(subtitle)}</p></div></div>`}
function renderFlow(arr){const grid=$('#flow-grid'),empty=$('#flow-empty');if(!arr.length){grid.innerHTML='';empty.classList.remove('hidden');return}empty.classList.add('hidden');const topInst=counts(arr,x=>x.further_study_institution)[0];const topStudy=counts(arr,x=>x.major||x.faculty)[0];const topCareer=counts(arr,x=>x.career_group||x.occupation)[0];grid.innerHTML=node('โรงเรียนวัดหนองแวงวิทยา',`${arr.length} เส้นทาง`,'school','orange')+node(topInst?.[0]||'ยังไม่ระบุสถาบัน',topInst?`${topInst[1]} คน • สถาบันที่พบมากที่สุด`:'','building-2','amber')+node(topStudy?.[0]||'ยังไม่ระบุสาขา',topStudy?`${topStudy[1]} คน • สาขาที่พบมากที่สุด`:'','book-open','slate')+node(topCareer?.[0]||'ยังไม่ระบุอาชีพ',topCareer?`${topCareer[1]} คน • กลุ่มอาชีพที่พบมากที่สุด`:'','briefcase-business','emerald')}
function renderRanking(id,data,accent='orange'){const box=$(id);const max=data[0]?.[1]||1;const theme=accent==='emerald'?{text:'text-emerald-600',bar:'bg-emerald-400'}:{text:'text-orange-600',bar:'bg-orange-400'};box.innerHTML=data.slice(0,7).map(([name,n],idx)=>`<div><div class="flex items-center justify-between gap-3 text-xs"><span class="font-bold text-slate-700 truncate"><span class="text-slate-400 mr-2">${idx+1}</span>${esc(name)}</span><span class="font-black ${theme.text}">${n}</span></div><div class="h-2 bg-slate-100 rounded-full mt-2 overflow-hidden"><div class="h-full ${theme.bar} rounded-full" style="width:${Math.max(7,n/max*100)}%"></div></div></div>`).join('')||'<p class="text-sm text-slate-400">ยังไม่มีข้อมูล</p>'}
function personCard(x){const study=[x.further_study_institution,x.faculty,x.major].filter(Boolean);const years=x.study_start_year||x.study_end_year?`พ.ศ. ${esc(x.study_start_year||'?')}–${esc(x.study_end_year||'?')}`:'';return `<a href="../?profile=${encodeURIComponent(x.id)}" class="path-card glass rounded-[2rem] p-5 block"><div class="flex gap-4 items-start"><img src="${esc(x.photo_url||placeholder(x.full_name))}" onerror="this.src='${placeholder(x.full_name)}'" class="w-20 h-20 rounded-2xl object-cover bg-orange-50 border border-orange-100"><div class="min-w-0 flex-1"><div class="flex flex-wrap gap-1.5"><span class="text-[10px] font-bold bg-orange-50 text-orange-700 border border-orange-100 px-2 py-1 rounded-full">${esc(x.batch||'ไม่ระบุรุ่น')}</span>${x.degree_level?`<span class="text-[10px] font-bold bg-slate-100 text-slate-600 px-2 py-1 rounded-full">${esc(x.degree_level)}</span>`:''}</div><h3 class="font-black text-slate-900 mt-2 line-clamp-2">${esc(x.full_name)}</h3>${years?`<p class="text-[11px] text-slate-400 mt-1">${years}</p>`:''}</div></div><div class="mt-4 space-y-2"><div class="flex items-start gap-2 text-xs"><i data-lucide="graduation-cap" class="w-4 h-4 text-orange-500 shrink-0 mt-0.5"></i><span class="text-slate-600">${esc(study.join(' • ')||'ยังไม่ระบุข้อมูลศึกษาต่อ')}</span></div><div class="flex items-start gap-2 text-xs"><i data-lucide="briefcase-business" class="w-4 h-4 text-emerald-600 shrink-0 mt-0.5"></i><span class="text-slate-600">${esc(x.current_position||x.occupation||x.career_group||'ยังไม่ระบุอาชีพ')}${x.organization?' • '+esc(x.organization):''}</span></div></div></a>`}
function render(){const arr=filtered();$('#filtered-count').textContent=`${arr.length.toLocaleString('th-TH')} คน`;renderFlow(arr);renderRanking('#institution-ranking',counts(arr,x=>x.further_study_institution),'orange');renderRanking('#career-ranking',counts(arr,x=>x.career_group||x.occupation),'emerald');const box=$('#person-list'),empty=$('#people-empty');if(!arr.length){box.innerHTML='';empty.classList.remove('hidden')}else{empty.classList.add('hidden');box.innerHTML=arr.map(personCard).join('')}lucide.createIcons()}
function renderError(msg){$('#flow-grid').innerHTML=`<div class="lg:col-span-4 glass rounded-[2rem] p-10 text-center text-red-600 font-bold">${esc(msg)}</div>`}
['#search','#batch-filter','#institution-filter','#career-filter'].forEach(s=>$(s).addEventListener(s==='#search'?'input':'change',render));load();
