-- ============================================================
-- Academic Department + Student Activities + Personnel Dharma levels
-- Wat Nongwang Wittaya School
-- Run once in Supabase SQL Editor
-- ============================================================

-- ---------- Academic announcements ----------
create table if not exists public.academic_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text default '',
  body text default '',
  publish_date date default current_date,
  pinned boolean not null default false,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.academic_posts enable row level security;
drop policy if exists "public read academic posts" on public.academic_posts;
create policy "public read academic posts" on public.academic_posts
for select to anon, authenticated using (published = true or public.is_site_admin());
drop policy if exists "admin insert academic posts" on public.academic_posts;
create policy "admin insert academic posts" on public.academic_posts
for insert to authenticated with check (public.is_site_admin());
drop policy if exists "admin update academic posts" on public.academic_posts;
create policy "admin update academic posts" on public.academic_posts
for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "admin delete academic posts" on public.academic_posts;
create policy "admin delete academic posts" on public.academic_posts
for delete to authenticated using (public.is_site_admin());

create index if not exists academic_posts_public_idx
on public.academic_posts (published, pinned desc, publish_date desc, sort_order asc);

-- ---------- Academic files ----------
create table if not exists public.academic_files (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'academic' check (category in ('academic','finance','quality','other')),
  description text default '',
  file_url text not null,
  file_name text default '',
  file_type text default '',
  file_size text default '',
  publish_date date default current_date,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.academic_files enable row level security;
drop policy if exists "public read academic files" on public.academic_files;
create policy "public read academic files" on public.academic_files
for select to anon, authenticated using (published = true or public.is_site_admin());
drop policy if exists "admin insert academic files" on public.academic_files;
create policy "admin insert academic files" on public.academic_files
for insert to authenticated with check (public.is_site_admin());
drop policy if exists "admin update academic files" on public.academic_files;
create policy "admin update academic files" on public.academic_files
for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "admin delete academic files" on public.academic_files;
create policy "admin delete academic files" on public.academic_files
for delete to authenticated using (public.is_site_admin());

create index if not exists academic_files_public_idx
on public.academic_files (published, category, publish_date desc, sort_order asc);

-- ---------- Student activities ----------
create table if not exists public.student_activity_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text default '',
  event_date date default current_date,
  image_position text not null default 'top' check (image_position in ('top','bottom')),
  featured boolean not null default false,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.student_activity_images (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.student_activity_posts(id) on delete cascade,
  image_url text not null,
  caption text default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.student_activity_posts enable row level security;
alter table public.student_activity_images enable row level security;

drop policy if exists "public read student activities" on public.student_activity_posts;
create policy "public read student activities" on public.student_activity_posts
for select to anon, authenticated using (published = true or public.is_site_admin());
drop policy if exists "admin insert student activities" on public.student_activity_posts;
create policy "admin insert student activities" on public.student_activity_posts
for insert to authenticated with check (public.is_site_admin());
drop policy if exists "admin update student activities" on public.student_activity_posts;
create policy "admin update student activities" on public.student_activity_posts
for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "admin delete student activities" on public.student_activity_posts;
create policy "admin delete student activities" on public.student_activity_posts
for delete to authenticated using (public.is_site_admin());

drop policy if exists "public read student activity images" on public.student_activity_images;
create policy "public read student activity images" on public.student_activity_images
for select to anon, authenticated using (
  exists (
    select 1 from public.student_activity_posts p
    where p.id = activity_id and (p.published = true or public.is_site_admin())
  )
);
drop policy if exists "admin insert student activity images" on public.student_activity_images;
create policy "admin insert student activity images" on public.student_activity_images
for insert to authenticated with check (public.is_site_admin());
drop policy if exists "admin update student activity images" on public.student_activity_images;
create policy "admin update student activity images" on public.student_activity_images
for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "admin delete student activity images" on public.student_activity_images;
create policy "admin delete student activity images" on public.student_activity_images
for delete to authenticated using (public.is_site_admin());

create index if not exists student_activity_posts_public_idx
on public.student_activity_posts (published, featured desc, event_date desc, sort_order asc);
create index if not exists student_activity_images_activity_idx
on public.student_activity_images (activity_id, sort_order asc);

-- ---------- Personnel: highest Naktham / Pali level ----------
alter table if exists public.personnel
  add column if not exists naktham_level text default '',
  add column if not exists pali_level text default '';

comment on column public.personnel.naktham_level is 'Highest Naktham level e.g. นักธรรมตรี/โท/เอก';
comment on column public.personnel.pali_level is 'Highest Pali level e.g. ประโยค 1-2, ป.ธ.3-9';

-- ---------- Grants ----------
grant select on public.academic_posts to anon, authenticated;
grant select on public.academic_files to anon, authenticated;
grant select on public.student_activity_posts to anon, authenticated;
grant select on public.student_activity_images to anon, authenticated;
grant insert, update, delete on public.academic_posts to authenticated;
grant insert, update, delete on public.academic_files to authenticated;
grant insert, update, delete on public.student_activity_posts to authenticated;
grant insert, update, delete on public.student_activity_images to authenticated;

grant usage, select on all sequences in schema public to authenticated;
