-- =====================================================================
-- Wat Nongwang Wittaya School
-- Academic + Student Activities + Personnel Dharma Levels
-- REPAIR / INSTALL V2
--
-- Designed for the current database schema. Safe to run more than once.
-- Fixes the earlier RLS issue where anonymous SELECT policies called
-- public.is_site_admin(), which can cause public pages to fail.
-- =====================================================================

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- 1) Website Manager authorization helper
--    All signed-in, non-anonymous Supabase Auth users are Website Managers.
-- ---------------------------------------------------------------------
create or replace function public.is_site_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select auth.uid() is not null
     and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false;
$$;

revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to authenticated;

-- ---------------------------------------------------------------------
-- 2) Shared updated_at trigger
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- 3) Academic announcements
-- ---------------------------------------------------------------------
create table if not exists public.academic_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text not null default '',
  body text not null default '',
  publish_date date not null default current_date,
  pinned boolean not null default false,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

-- Repair a partially-created table from an older SQL run.
alter table public.academic_posts add column if not exists summary text not null default '';
alter table public.academic_posts add column if not exists body text not null default '';
alter table public.academic_posts add column if not exists publish_date date not null default current_date;
alter table public.academic_posts add column if not exists pinned boolean not null default false;
alter table public.academic_posts add column if not exists published boolean not null default true;
alter table public.academic_posts add column if not exists sort_order integer not null default 0;
alter table public.academic_posts add column if not exists created_at timestamptz not null default now();
alter table public.academic_posts add column if not exists updated_at timestamptz not null default now();
alter table public.academic_posts add column if not exists created_by uuid;

create index if not exists academic_posts_public_idx
  on public.academic_posts (published, pinned desc, publish_date desc, sort_order asc);

alter table public.academic_posts enable row level security;

-- Remove policies from the previous version and recreate them separately.
drop policy if exists "public read academic posts" on public.academic_posts;
drop policy if exists "public read published academic posts" on public.academic_posts;
drop policy if exists "admin read all academic posts" on public.academic_posts;
drop policy if exists "admin insert academic posts" on public.academic_posts;
drop policy if exists "admin update academic posts" on public.academic_posts;
drop policy if exists "admin delete academic posts" on public.academic_posts;

-- IMPORTANT: public policy never calls is_site_admin().
create policy "public read published academic posts"
on public.academic_posts
for select
to anon, authenticated
using (published = true);

create policy "admin read all academic posts"
on public.academic_posts
for select
to authenticated
using (public.is_site_admin());

create policy "admin insert academic posts"
on public.academic_posts
for insert
to authenticated
with check (public.is_site_admin());

create policy "admin update academic posts"
on public.academic_posts
for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

create policy "admin delete academic posts"
on public.academic_posts
for delete
to authenticated
using (public.is_site_admin());

-- ---------------------------------------------------------------------
-- 4) Academic documents: academic / finance / quality / other
-- ---------------------------------------------------------------------
create table if not exists public.academic_files (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'academic',
  description text not null default '',
  file_url text not null,
  file_name text not null default '',
  file_type text not null default '',
  file_size text not null default '',
  publish_date date not null default current_date,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.academic_files add column if not exists category text not null default 'academic';
alter table public.academic_files add column if not exists description text not null default '';
alter table public.academic_files add column if not exists file_name text not null default '';
alter table public.academic_files add column if not exists file_type text not null default '';
alter table public.academic_files add column if not exists file_size text not null default '';
alter table public.academic_files add column if not exists publish_date date not null default current_date;
alter table public.academic_files add column if not exists published boolean not null default true;
alter table public.academic_files add column if not exists sort_order integer not null default 0;
alter table public.academic_files add column if not exists created_at timestamptz not null default now();
alter table public.academic_files add column if not exists updated_at timestamptz not null default now();
alter table public.academic_files add column if not exists created_by uuid;

-- Normalize invalid legacy values before applying the check constraint.
update public.academic_files
set category = 'other'
where category is null or category not in ('academic','finance','quality','other');

alter table public.academic_files
  drop constraint if exists academic_files_category_check;
alter table public.academic_files
  add constraint academic_files_category_check
  check (category in ('academic','finance','quality','other'));

create index if not exists academic_files_public_idx
  on public.academic_files (published, category, publish_date desc, sort_order asc);

alter table public.academic_files enable row level security;

drop policy if exists "public read academic files" on public.academic_files;
drop policy if exists "public read published academic files" on public.academic_files;
drop policy if exists "admin read all academic files" on public.academic_files;
drop policy if exists "admin insert academic files" on public.academic_files;
drop policy if exists "admin update academic files" on public.academic_files;
drop policy if exists "admin delete academic files" on public.academic_files;

create policy "public read published academic files"
on public.academic_files
for select
to anon, authenticated
using (published = true);

create policy "admin read all academic files"
on public.academic_files
for select
to authenticated
using (public.is_site_admin());

create policy "admin insert academic files"
on public.academic_files
for insert
to authenticated
with check (public.is_site_admin());

create policy "admin update academic files"
on public.academic_files
for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

create policy "admin delete academic files"
on public.academic_files
for delete
to authenticated
using (public.is_site_admin());

-- ---------------------------------------------------------------------
-- 5) Student activity posts
-- ---------------------------------------------------------------------
create table if not exists public.student_activity_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  event_date date not null default current_date,
  image_position text not null default 'top',
  featured boolean not null default false,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.student_activity_posts add column if not exists body text not null default '';
alter table public.student_activity_posts add column if not exists event_date date not null default current_date;
alter table public.student_activity_posts add column if not exists image_position text not null default 'top';
alter table public.student_activity_posts add column if not exists featured boolean not null default false;
alter table public.student_activity_posts add column if not exists published boolean not null default true;
alter table public.student_activity_posts add column if not exists sort_order integer not null default 0;
alter table public.student_activity_posts add column if not exists created_at timestamptz not null default now();
alter table public.student_activity_posts add column if not exists updated_at timestamptz not null default now();
alter table public.student_activity_posts add column if not exists created_by uuid;

update public.student_activity_posts
set image_position = 'top'
where image_position is null or image_position not in ('top','bottom');

alter table public.student_activity_posts
  drop constraint if exists student_activity_posts_image_position_check;
alter table public.student_activity_posts
  add constraint student_activity_posts_image_position_check
  check (image_position in ('top','bottom'));

create index if not exists student_activity_posts_public_idx
  on public.student_activity_posts (published, featured desc, event_date desc, sort_order asc);

alter table public.student_activity_posts enable row level security;

drop policy if exists "public read student activities" on public.student_activity_posts;
drop policy if exists "public read published student activities" on public.student_activity_posts;
drop policy if exists "admin read all student activities" on public.student_activity_posts;
drop policy if exists "admin insert student activities" on public.student_activity_posts;
drop policy if exists "admin update student activities" on public.student_activity_posts;
drop policy if exists "admin delete student activities" on public.student_activity_posts;

create policy "public read published student activities"
on public.student_activity_posts
for select
to anon, authenticated
using (published = true);

create policy "admin read all student activities"
on public.student_activity_posts
for select
to authenticated
using (public.is_site_admin());

create policy "admin insert student activities"
on public.student_activity_posts
for insert
to authenticated
with check (public.is_site_admin());

create policy "admin update student activities"
on public.student_activity_posts
for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

create policy "admin delete student activities"
on public.student_activity_posts
for delete
to authenticated
using (public.is_site_admin());

-- ---------------------------------------------------------------------
-- 6) Multiple ordered images for each student activity
-- ---------------------------------------------------------------------
create table if not exists public.student_activity_images (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.student_activity_posts(id) on delete cascade,
  image_url text not null,
  caption text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.student_activity_images add column if not exists caption text not null default '';
alter table public.student_activity_images add column if not exists sort_order integer not null default 0;
alter table public.student_activity_images add column if not exists created_at timestamptz not null default now();

create index if not exists student_activity_images_activity_idx
  on public.student_activity_images (activity_id, sort_order asc);

alter table public.student_activity_images enable row level security;

drop policy if exists "public read student activity images" on public.student_activity_images;
drop policy if exists "public read published student activity images" on public.student_activity_images;
drop policy if exists "admin read all student activity images" on public.student_activity_images;
drop policy if exists "admin insert student activity images" on public.student_activity_images;
drop policy if exists "admin update student activity images" on public.student_activity_images;
drop policy if exists "admin delete student activity images" on public.student_activity_images;

create policy "public read published student activity images"
on public.student_activity_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.student_activity_posts p
    where p.id = student_activity_images.activity_id
      and p.published = true
  )
);

create policy "admin read all student activity images"
on public.student_activity_images
for select
to authenticated
using (public.is_site_admin());

create policy "admin insert student activity images"
on public.student_activity_images
for insert
to authenticated
with check (public.is_site_admin());

create policy "admin update student activity images"
on public.student_activity_images
for update
to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

create policy "admin delete student activity images"
on public.student_activity_images
for delete
to authenticated
using (public.is_site_admin());

-- ---------------------------------------------------------------------
-- 7) Personnel: highest Naktham / Pali level
-- ---------------------------------------------------------------------
alter table if exists public.personnel
  add column if not exists naktham_level text not null default '';

alter table if exists public.personnel
  add column if not exists pali_level text not null default '';

comment on column public.personnel.naktham_level is
  'Highest Naktham level: นักธรรมตรี / นักธรรมโท / นักธรรมเอก';
comment on column public.personnel.pali_level is
  'Highest Pali level: ประโยค 1-2 / ป.ธ.3 ... ป.ธ.9';

-- ---------------------------------------------------------------------
-- 8) updated_at triggers
-- ---------------------------------------------------------------------
drop trigger if exists academic_posts_set_updated_at on public.academic_posts;
create trigger academic_posts_set_updated_at
before update on public.academic_posts
for each row execute function public.set_updated_at();

drop trigger if exists academic_files_set_updated_at on public.academic_files;
create trigger academic_files_set_updated_at
before update on public.academic_files
for each row execute function public.set_updated_at();

drop trigger if exists student_activity_posts_set_updated_at on public.student_activity_posts;
create trigger student_activity_posts_set_updated_at
before update on public.student_activity_posts
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------
-- 9) API privileges
-- ---------------------------------------------------------------------
grant usage on schema public to anon, authenticated;

grant select on public.academic_posts to anon, authenticated;
grant select on public.academic_files to anon, authenticated;
grant select on public.student_activity_posts to anon, authenticated;
grant select on public.student_activity_images to anon, authenticated;

grant insert, update, delete on public.academic_posts to authenticated;
grant insert, update, delete on public.academic_files to authenticated;
grant insert, update, delete on public.student_activity_posts to authenticated;
grant insert, update, delete on public.student_activity_images to authenticated;

grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------
-- 10) site-media bucket used by Academic files and Activity images
-- ---------------------------------------------------------------------
insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
values (
  'site-media',
  'site-media',
  true,
  20971520,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain',
    'text/csv',
    'application/csv',
    'application/octet-stream'
  ]::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Storage public read does not call is_site_admin().
drop policy if exists "public read site media" on storage.objects;
create policy "public read site media"
on storage.objects
for select
using (bucket_id = 'site-media');

drop policy if exists "admin upload site media" on storage.objects;
create policy "admin upload site media"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'site-media' and public.is_site_admin());

drop policy if exists "admin update site media" on storage.objects;
create policy "admin update site media"
on storage.objects
for update
to authenticated
using (bucket_id = 'site-media' and public.is_site_admin())
with check (bucket_id = 'site-media' and public.is_site_admin());

drop policy if exists "admin delete site media" on storage.objects;
create policy "admin delete site media"
on storage.objects
for delete
to authenticated
using (bucket_id = 'site-media' and public.is_site_admin());

commit;

-- ---------------------------------------------------------------------
-- Verification: the result grid should show 4 tables + 2 personnel fields.
-- ---------------------------------------------------------------------
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'academic_posts',
    'academic_files',
    'student_activity_posts',
    'student_activity_images'
  )
order by table_name;

select column_name, data_type
from information_schema.columns
where table_schema = 'public'
  and table_name = 'personnel'
  and column_name in ('naktham_level','pali_level')
order by column_name;
