-- ============================================================
-- Supabase Upgrade: Alumni Self-Registration + Review Queue
-- Wat Nongwang Wittaya School
-- Run in Supabase > SQL Editor. Safe to run again.
-- ============================================================

create extension if not exists pgcrypto;

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select auth.uid() is not null
     and coalesce((auth.jwt()->>'is_anonymous')::boolean, false) = false;
$$;

revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to authenticated;

create table if not exists public.alumni_submissions (
  id uuid primary key default gen_random_uuid(),
  submission_no bigint generated by default as identity unique,
  submission_state text not null default 'uploading'
    check (submission_state in ('uploading','submitted')),
  review_status text not null default 'pending'
    check (review_status in ('pending','approved','rejected')),

  full_name text not null,
  batch text not null,
  graduation_year text not null default '',
  graduation_level text not null default '',
  current_position text not null default '',
  occupation text not null default '',
  organization text not null default '',
  education text not null default '',
  phone text not null default '',
  email text not null default '',
  facebook_url text not null default '',
  bio text not null default '',
  show_contact boolean not null default false,

  photo_url text not null default '',
  photo_path text not null default '',

  consent_accepted boolean not null default false,
  consent_accepted_at timestamptz,
  submitted_at timestamptz,
  upload_token uuid,

  admin_note text not null default '',
  reviewed_at timestamptz,
  reviewed_by uuid,
  approved_alumni_id uuid references public.alumni(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.alumni_submissions add column if not exists featured boolean not null default false;

create index if not exists alumni_submissions_status_idx
  on public.alumni_submissions (review_status, submitted_at desc);
create index if not exists alumni_submissions_batch_idx
  on public.alumni_submissions (batch);
create index if not exists alumni_submissions_name_idx
  on public.alumni_submissions (full_name);

alter table public.alumni_submissions enable row level security;

-- Public users do not read/write the table directly. They use security-definer RPCs.
drop policy if exists "admin read alumni submissions" on public.alumni_submissions;
create policy "admin read alumni submissions"
on public.alumni_submissions for select to authenticated
using (public.is_site_admin());

drop policy if exists "admin update alumni submissions" on public.alumni_submissions;
create policy "admin update alumni submissions"
on public.alumni_submissions for update to authenticated
using (public.is_site_admin())
with check (public.is_site_admin());

drop policy if exists "admin delete alumni submissions" on public.alumni_submissions;
create policy "admin delete alumni submissions"
on public.alumni_submissions for delete to authenticated
using (public.is_site_admin());

grant select, update, delete on public.alumni_submissions to authenticated;

-- Keep updated_at fresh.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists alumni_submissions_updated_at on public.alumni_submissions;
create trigger alumni_submissions_updated_at
before update on public.alumni_submissions
for each row execute function public.set_updated_at();

-- ---------- Public: start a submission ----------
create or replace function public.create_alumni_submission(p_payload jsonb)
returns table(id uuid, submission_no bigint, upload_token uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.alumni_submissions;
begin
  if coalesce((p_payload->>'consentAccepted')::boolean, false) is not true then
    raise exception 'กรุณายอมรับเงื่อนไขการส่งข้อมูลก่อน';
  end if;
  if coalesce(btrim(p_payload->>'fullName'),'') = '' then
    raise exception 'กรุณาระบุชื่อ-นามสกุล';
  end if;
  if coalesce(btrim(p_payload->>'batch'),'') = '' then
    raise exception 'กรุณาระบุรุ่นศิษย์เก่า';
  end if;
  if coalesce(btrim(p_payload->>'phone'),'') = '' and coalesce(btrim(p_payload->>'email'),'') = '' then
    raise exception 'กรุณาระบุเบอร์โทรศัพท์หรือ Email อย่างน้อย 1 ช่อง';
  end if;

  insert into public.alumni_submissions (
    submission_state, review_status,
    full_name, batch, graduation_year, graduation_level,
    current_position, occupation, organization, education,
    phone, email, facebook_url, bio, show_contact,
    photo_url,
    consent_accepted, consent_accepted_at,
    upload_token
  ) values (
    'uploading', 'pending',
    btrim(p_payload->>'fullName'), btrim(p_payload->>'batch'),
    coalesce(btrim(p_payload->>'graduationYear'),''),
    coalesce(btrim(p_payload->>'graduationLevel'),''),
    coalesce(btrim(p_payload->>'currentPosition'),''),
    coalesce(btrim(p_payload->>'occupation'),''),
    coalesce(btrim(p_payload->>'organization'),''),
    coalesce(p_payload->>'education',''),
    coalesce(btrim(p_payload->>'phone'),''),
    coalesce(btrim(p_payload->>'email'),''),
    coalesce(btrim(p_payload->>'facebookUrl'),''),
    coalesce(p_payload->>'bio',''),
    coalesce((p_payload->>'showContact')::boolean,false),
    coalesce(btrim(p_payload->>'photoUrl'),''),
    true, now(), gen_random_uuid()
  ) returning * into v_row;

  return query select v_row.id, v_row.submission_no, v_row.upload_token;
end;
$$;

revoke all on function public.create_alumni_submission(jsonb) from public;
grant execute on function public.create_alumni_submission(jsonb) to anon, authenticated;

-- ---------- Public upload authorization ----------
-- Object path must be: <submission-id>/<upload-token>/<filename>
create or replace function public.can_upload_alumni_submission_file(object_name text)
returns boolean
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_id uuid;
  v_token uuid;
begin
  begin
    v_id := split_part(object_name, '/', 1)::uuid;
    v_token := split_part(object_name, '/', 2)::uuid;
  exception when others then
    return false;
  end;

  return exists (
    select 1
    from public.alumni_submissions s
    where s.id = v_id
      and s.upload_token = v_token
      and s.submission_state = 'uploading'
  );
end;
$$;

revoke all on function public.can_upload_alumni_submission_file(text) from public;
grant execute on function public.can_upload_alumni_submission_file(text) to anon, authenticated;

-- ---------- Public: finalize after optional photo upload ----------
create or replace function public.finalize_alumni_submission(
  p_id uuid,
  p_upload_token uuid,
  p_photo_path text default ''
)
returns table(submission_no bigint, submitted_at timestamptz, review_status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.alumni_submissions;
begin
  update public.alumni_submissions
  set photo_path = coalesce(p_photo_path,''),
      submission_state = 'submitted',
      submitted_at = now(),
      upload_token = null
  where id = p_id
    and upload_token = p_upload_token
    and submission_state = 'uploading'
  returning * into v_row;

  if v_row.id is null then
    raise exception 'ไม่สามารถยืนยันข้อมูลได้ กรุณาลองใหม่';
  end if;

  return query select v_row.submission_no, v_row.submitted_at, v_row.review_status;
end;
$$;

revoke all on function public.finalize_alumni_submission(uuid,uuid,text) from public;
grant execute on function public.finalize_alumni_submission(uuid,uuid,text) to anon, authenticated;

-- ---------- Private storage bucket for submitted photos ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'alumni-submission-files',
  'alumni-submission-files',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public upload alumni submission files" on storage.objects;
create policy "public upload alumni submission files"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'alumni-submission-files'
  and public.can_upload_alumni_submission_file(name)
);

drop policy if exists "admin read alumni submission files" on storage.objects;
create policy "admin read alumni submission files"
on storage.objects for select
to authenticated
using (bucket_id = 'alumni-submission-files' and public.is_site_admin());

drop policy if exists "admin update alumni submission files" on storage.objects;
create policy "admin update alumni submission files"
on storage.objects for update
to authenticated
using (bucket_id = 'alumni-submission-files' and public.is_site_admin())
with check (bucket_id = 'alumni-submission-files' and public.is_site_admin());

drop policy if exists "admin delete alumni submission files" on storage.objects;
create policy "admin delete alumni submission files"
on storage.objects for delete
to authenticated
using (bucket_id = 'alumni-submission-files' and public.is_site_admin());

comment on table public.alumni_submissions is
'Public alumni self-registration queue. Admin reviews/edits before approving into public.alumni.';
