const db=window.SCHOOL_SUPABASE, BUCKET='student-portal-files';
let students=[],timetables=[],exams=[],grades=[];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dayOrder={จันทร์:1,อังคาร:2,พุธ:3,พฤหัสบดี:4,ศุกร์:5,เสาร์:6,อาทิตย์:7};
window.addEventListener('DOMContentLoaded',init);
async function init(){lucide.createIcons();bind();if(!db)return;const {data:{session}}=await db.auth.getSession();if(session)await enterApp(session.user);db.auth.onAuthStateChange((_e,s)=>{if(s?.user&&!$('loginScreen').classList.contains('hide'))enterApp(s.user)})}
function bind(){ $('adminLoginForm').addEventListener('submit',adminLogin);$('studentForm').addEventListener('submit',saveStudent);$('timetableForm').addEventListener('submit',saveTimetable);$('examForm').addEventListener('submit',saveExam);$('studentExcelInput').addEventListener('change',importStudents);$('timetableExcelInput').addEventListener('change',importTimetable);$('examExcelInput').addEventListener('change',importExams);['studentSearch','studentClassFilter','studentStatusFilter'].forEach(id=>$(id).addEventListener('input',renderStudents));['ttClassFilter','ttDayFilter'].forEach(id=>$(id).addEventListener('input',renderTimetables));$('examClassFilter').addEventListener('input',renderExams);['gradeSearch','gradeClassFilter'].forEach(id=>$(id).addEventListener('input',renderGrades));}
async function adminLogin(e){e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('adminEmail').value,password:$('adminPassword').value});if(error){$('adminLoginMsg').textContent=error.message;$('adminLoginMsg').className='text-sm text-center mt-3 text-red-600';return}await enterApp(data.user)}
async function enterApp(user){$('loginScreen').classList.add('hide');$('app').classList.remove('hide');$('adminIdentity').textContent=user.email||'';await reloadAll();}
window.adminLogout=async()=>{await db.auth.signOut();location.reload()};window.toggleSidebar=()=>$('sidebar').classList.toggle('open');
window.openPage=p=>{document.querySelectorAll('.page-section').forEach(x=>x.classList.add('hide'));$(`page-${p}`).classList.remove('hide');document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('pageTitle').textContent=({dashboard:'Dashboard',students:'นักเรียน',timetable:'ตารางเรียน',exams:'วันสอบ',grades:'ไฟล์เกรด'})[p];$('sidebar').classList.remove('open');lucide.createIcons()};
async function reloadAll(){await Promise.all([loadStudents(),loadTimetables(),loadExams(),loadGrades()]);renderDashboard();}
async function loadStudents(){const {data,error}=await db.from('students').select('id,student_code,title,first_name,last_name,class_level,room,phone,email,photo_path,storage_key,active,created_at,updated_at').order('class_level').order('student_code');if(error){console.error(error);return}students=data||[];renderStudents()}
async function loadTimetables(){const {data,error}=await db.from('student_timetables').select('*').order('day_order').order('start_time');if(error)return console.error(error);timetables=data||[];renderTimetables()}
async function loadExams(){const {data,error}=await db.from('student_exams').select('*').order('exam_date').order('start_time');if(error)return console.error(error);exams=data||[];renderExams()}
async function loadGrades(){const {data,error}=await db.from('student_grade_uploads').select('id,student_id,academic_year,semester,file_path,original_file_name,note,uploaded_at,students(student_code,title,first_name,last_name,class_level)').order('uploaded_at',{ascending:false});if(error)return console.error(error);grades=data||[];renderGrades()}
function renderDashboard(){const active=students.filter(x=>x.active).length;const today=new Date().toISOString().slice(0,10);const upcoming=exams.filter(x=>x.exam_date>=today).length;const cards=[[students.length,'นักเรียนทั้งหมด','users','bg-orange-50 text-orange-600'],[active,'เปิดใช้งาน Portal','user-check','bg-emerald-50 text-emerald-600'],[timetables.length,'คาบเรียน','calendar-range','bg-sky-50 text-sky-600'],[upcoming,'รายการสอบที่กำลังจะถึง','clipboard-check','bg-violet-50 text-violet-600']];$('statCards').innerHTML=cards.map(([v,l,i,cls])=>`<div class="card rounded-3xl p-5"><div class="w-11 h-11 rounded-xl ${cls} flex items-center justify-center mb-4"><i data-lucide="${i}" class="w-5 h-5"></i></div><p class="text-3xl font-black">${v}</p><p class="text-sm text-slate-500 mt-1">${l}</p></div>`).join('');$('classSummary').innerHTML=['ม.1','ม.2','ม.3','ม.4','ม.5','ม.6'].map(c=>`<button onclick="filterClass('${c}')" class="p-4 rounded-2xl bg-slate-50 hover:bg-orange-50 text-left"><p class="text-xs text-slate-500">${c}</p><p class="text-2xl font-black mt-1">${students.filter(s=>s.class_level===c).length}</p></button>`).join('');lucide.createIcons()}
window.filterClass=c=>{openPage('students');$('studentClassFilter').value=c;renderStudents()};
function renderStudents(){const q=$('studentSearch').value.toLowerCase(),cl=$('studentClassFilter').value,st=$('studentStatusFilter').value;const rows=students.filter(s=>(!cl||s.class_level===cl)&&(!st||(st==='active'?s.active:!s.active))&&`${s.student_code} ${s.first_name} ${s.last_name} ${s.phone||''} ${s.email||''}`.toLowerCase().includes(q));$('studentTable').innerHTML=rows.length?rows.map(s=>`<tr class="border-t border-slate-100 hover:bg-slate-50"><td class="p-4 font-mono font-bold">${esc(s.student_code)}</td><td class="p-4"><p class="font-bold">${esc([s.title,s.first_name,s.last_name].filter(Boolean).join(' '))}</p></td><td class="p-4"><span class="px-2.5 py-1 rounded-full bg-orange-50 text-orange-700 font-bold text-xs">${esc(s.class_level)}${s.room?' / '+esc(s.room):''}</span></td><td class="p-4 text-xs text-slate-500"><p>${esc(s.phone||'–')}</p><p>${esc(s.email||'–')}</p></td><td class="p-4 text-center"><span class="px-2 py-1 rounded-full text-[10px] font-bold ${s.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}">${s.active?'ใช้งาน':'ปิด'}</span></td><td class="p-4 text-right whitespace-nowrap"><button onclick="editStudent('${s.id}')" class="px-2 py-1 text-sky-600 font-bold">แก้ไข</button><button onclick="resetPin('${s.id}')" class="px-2 py-1 text-amber-600 font-bold">PIN</button><button onclick="deleteStudent('${s.id}')" class="px-2 py-1 text-red-500 font-bold">ลบ</button></td></tr>`).join(''):'<tr><td colspan="6" class="p-8 text-center text-slate-400">ไม่พบข้อมูล</td></tr>'}
window.openStudentModal=()=>{ $('studentForm').reset();$('studentId').value='';$('fStudentActive').checked=true;$('studentModalTitle').textContent='เพิ่มนักเรียน';$('studentModal').classList.remove('hide')};window.editStudent=id=>{const s=students.find(x=>x.id===id);if(!s)return;openStudentModal();$('studentId').value=s.id;$('studentModalTitle').textContent='แก้ไขนักเรียน';$('fStudentCode').value=s.student_code;$('fStudentTitle').value=s.title||'สามเณร';$('fStudentFirst').value=s.first_name;$('fStudentLast').value=s.last_name;$('fStudentClass').value=s.class_level;$('fStudentRoom').value=s.room||'';$('fStudentPhone').value=s.phone||'';$('fStudentEmail').value=s.email||'';$('fStudentPin').value='';$('fStudentActive').checked=s.active};window.closeModal=id=>$(id).classList.add('hide');
async function saveStudent(e){e.preventDefault();const isNew=!$('studentId').value;if(isNew&&$('fStudentPin').value.length<6)return alert('กรุณากำหนด PIN เริ่มต้นอย่างน้อย 6 ตัวอักษร');const row={student_code:$('fStudentCode').value.trim(),title:$('fStudentTitle').value,first_name:$('fStudentFirst').value.trim(),last_name:$('fStudentLast').value.trim(),class_level:$('fStudentClass').value,room:$('fStudentRoom').value.trim(),phone:$('fStudentPhone').value.trim(),email:$('fStudentEmail').value.trim(),portal_pin:$('fStudentPin').value.trim(),active:$('fStudentActive').checked};const {data,error}=await db.rpc('manager_import_students',{p_rows:[row]});if(error)return alert(error.message);closeModal('studentModal');await loadStudents();renderDashboard()}
window.resetPin=async id=>{const pin=prompt('กำหนด PIN ใหม่ (อย่างน้อย 6 ตัวอักษร)');if(!pin)return;const {data,error}=await db.rpc('manager_reset_student_pin',{p_student_id:id,p_new_pin:pin});if(error||!data?.ok)return alert(data?.message||error?.message);alert('เปลี่ยน PIN แล้ว')};window.deleteStudent=async id=>{if(!confirm('ลบนักเรียนรายนี้และข้อมูลที่เกี่ยวข้องทั้งหมดหรือไม่?'))return;const {error}=await db.from('students').delete().eq('id',id);if(error)return alert(error.message);await reloadAll()};

async function importStudents(e){const f=e.target.files[0];e.target.value='';if(!f)return;try{const rows=await sheetRows(f,2);const norm=rows.map(r=>({student_code:txt(r['รหัสนักเรียน']??r.student_code),title:txt(r['คำนำหน้า']??r.title),first_name:txt(r['ชื่อ']??r.first_name),last_name:txt(r['นามสกุล']??r.last_name),class_level:txt(r['ระดับชั้น']??r.class_level),room:txt(r['ห้อง']??r.room),phone:txt(r['เบอร์โทรศัพท์']??r.phone),email:txt(r['Email']??r.email),portal_pin:txt(r['PIN เริ่มต้น']??r.portal_pin),active:true})).filter(r=>r.student_code);const bad=norm.filter(r=>!r.first_name||!r.last_name||!['ม.1','ม.2','ม.3','ม.4','ม.5','ม.6'].includes(r.class_level));if(bad.length)return alert(`พบข้อมูลไม่ครบ/ระดับชั้นไม่ถูกต้อง ${bad.length} แถว`);if(!confirm(`นำเข้านักเรียน ${norm.length} รายการ? รหัสซ้ำจะอัปเดตข้อมูลเดิม`))return;const {data,error}=await db.rpc('manager_import_students',{p_rows:norm});if(error)throw error;const generated=(data?.rows||[]).filter(x=>x.generated_pin);if(generated.length){downloadCsv('generated-student-pins.csv',['student_code','generated_pin'],generated);alert(`นำเข้าสำเร็จ และมี ${generated.length} รายการที่ระบบสร้าง PIN ให้ ดาวน์โหลดไฟล์ PIN แล้ว`)}else alert('นำเข้าสำเร็จ');await loadStudents();renderDashboard()}catch(err){alert('อ่านไฟล์ไม่สำเร็จ: '+err.message)}}

function renderTimetables(){const cl=$('ttClassFilter').value,day=$('ttDayFilter').value;const rows=timetables.filter(x=>(!cl||x.class_level===cl)&&(!day||x.day_name===day));$('timetableTable').innerHTML=rows.length?rows.map(x=>`<tr class="border-t"><td class="p-3 font-bold">${esc(x.class_level)}</td><td class="p-3">${esc(x.day_name)}</td><td class="p-3 font-mono">${esc((x.start_time||'').slice(0,5))}–${esc((x.end_time||'').slice(0,5))}</td><td class="p-3">${esc(x.subject_code||'')}</td><td class="p-3 font-bold">${esc(x.subject_name)}</td><td class="p-3">${esc(x.teacher_name||'')}</td><td class="p-3 text-right"><button onclick="editTimetable('${x.id}')" class="text-sky-600 font-bold mr-2">แก้</button><button onclick="deleteTimetable('${x.id}')" class="text-red-500 font-bold">ลบ</button></td></tr>`).join(''):'<tr><td colspan="7" class="p-8 text-center text-slate-400">ไม่มีข้อมูล</td></tr>'}
window.openTimetableModal=()=>{$('timetableForm').reset();$('ttId').value='';$('ttPublished').checked=true;$('timetableModal').classList.remove('hide')};window.editTimetable=id=>{const x=timetables.find(r=>r.id===id);if(!x)return;openTimetableModal();[['ttId',x.id],['ttClass',x.class_level],['ttDay',x.day_name],['ttPeriod',x.period_no],['ttStart',(x.start_time||'').slice(0,5)],['ttEnd',(x.end_time||'').slice(0,5)],['ttSubjectCode',x.subject_code],['ttSubjectName',x.subject_name],['ttTeacher',x.teacher_name],['ttRoom',x.room],['ttSemester',x.semester],['ttYear',x.academic_year]].forEach(([id,v])=>$(id).value=v??'');$('ttPublished').checked=x.published};
async function saveTimetable(e){e.preventDefault();const row={class_level:$('ttClass').value,day_name:$('ttDay').value,day_order:dayOrder[$('ttDay').value],period_no:numOrNull($('ttPeriod').value),start_time:$('ttStart').value,end_time:$('ttEnd').value||null,subject_code:$('ttSubjectCode').value.trim()||null,subject_name:$('ttSubjectName').value.trim(),teacher_name:$('ttTeacher').value.trim()||null,room:$('ttRoom').value.trim()||null,semester:$('ttSemester').value.trim()||null,academic_year:$('ttYear').value.trim()||null,published:$('ttPublished').checked};const id=$('ttId').value;const q=id?db.from('student_timetables').update(row).eq('id',id):db.from('student_timetables').insert(row);const {error}=await q;if(error)return alert(error.message);closeModal('timetableModal');await loadTimetables();renderDashboard()}
window.deleteTimetable=async id=>{if(!confirm('ลบคาบเรียนนี้?'))return;const {error}=await db.from('student_timetables').delete().eq('id',id);if(error)return alert(error.message);await loadTimetables()};
async function importTimetable(e){const f=e.target.files[0];e.target.value='';if(!f)return;try{const raw=await sheetRows(f,2);const rows=raw.map(r=>({class_level:txt(r['ระดับชั้น']),day_name:txt(r['วัน']),day_order:dayOrder[txt(r['วัน'])],period_no:numOrNull(r['ลำดับคาบ']),start_time:normTime(r['เวลาเริ่ม']),end_time:normTime(r['เวลาสิ้นสุด'])||null,subject_code:txt(r['รหัสวิชา'])||null,subject_name:txt(r['วิชา']),teacher_name:txt(r['ครูผู้สอน'])||null,room:txt(r['ห้องเรียน'])||null,semester:txt(r['ภาคเรียน'])||null,academic_year:txt(r['ปีการศึกษา'])||null,published:true})).filter(r=>r.class_level&&r.day_name&&r.start_time&&r.subject_name);if(!rows.length)return alert('ไม่พบแถวข้อมูลที่ถูกต้อง');if(!confirm(`นำเข้าตารางเรียน ${rows.length} คาบ?`))return;if($('ttReplace').checked)await deleteExistingGroups('student_timetables',rows);for(const chunk of chunks(rows,400)){const {error}=await db.from('student_timetables').insert(chunk);if(error)throw error}alert('นำเข้าตารางเรียนเรียบร้อย');await loadTimetables();renderDashboard()}catch(err){alert(err.message)}}

function renderExams(){const cl=$('examClassFilter').value;const rows=exams.filter(x=>!cl||x.class_level===cl);$('examTable').innerHTML=rows.length?rows.map(x=>`<tr class="border-t"><td class="p-3 font-bold">${esc(x.class_level)}</td><td class="p-3">${esc(x.exam_date)}</td><td class="p-3 font-mono">${esc((x.start_time||'').slice(0,5))}${x.end_time?'–'+esc(x.end_time.slice(0,5)):''}</td><td class="p-3 font-bold">${esc(x.subject_name)}</td><td class="p-3">${esc(x.exam_type||'')}</td><td class="p-3">${esc(x.room||'')}</td><td class="p-3 text-right"><button onclick="editExam('${x.id}')" class="text-sky-600 font-bold mr-2">แก้</button><button onclick="deleteExam('${x.id}')" class="text-red-500 font-bold">ลบ</button></td></tr>`).join(''):'<tr><td colspan="7" class="p-8 text-center text-slate-400">ไม่มีข้อมูล</td></tr>'}
window.openExamModal=()=>{$('examForm').reset();$('examId').value='';$('examPublished').checked=true;$('examModal').classList.remove('hide')};window.editExam=id=>{const x=exams.find(r=>r.id===id);if(!x)return;openExamModal();[['examId',x.id],['examClass',x.class_level],['examDate',x.exam_date],['examStart',(x.start_time||'').slice(0,5)],['examEnd',(x.end_time||'').slice(0,5)],['examSubjectCode',x.subject_code],['examSubjectName',x.subject_name],['examType',x.exam_type],['examRoom',x.room],['examSemester',x.semester],['examYear',x.academic_year],['examNote',x.note]].forEach(([id,v])=>$(id).value=v??'');$('examPublished').checked=x.published};
async function saveExam(e){e.preventDefault();const row={class_level:$('examClass').value,exam_date:$('examDate').value,start_time:$('examStart').value||null,end_time:$('examEnd').value||null,subject_code:$('examSubjectCode').value.trim()||null,subject_name:$('examSubjectName').value.trim(),exam_type:$('examType').value.trim()||null,room:$('examRoom').value.trim()||null,note:$('examNote').value.trim()||null,semester:$('examSemester').value.trim()||null,academic_year:$('examYear').value.trim()||null,published:$('examPublished').checked};const id=$('examId').value;const q=id?db.from('student_exams').update(row).eq('id',id):db.from('student_exams').insert(row);const {error}=await q;if(error)return alert(error.message);closeModal('examModal');await loadExams();renderDashboard()}
window.deleteExam=async id=>{if(!confirm('ลบกำหนดการสอบนี้?'))return;const {error}=await db.from('student_exams').delete().eq('id',id);if(error)return alert(error.message);await loadExams()};
async function importExams(e){const f=e.target.files[0];e.target.value='';if(!f)return;try{const raw=await sheetRows(f,2);const rows=raw.map(r=>({class_level:txt(r['ระดับชั้น']),exam_date:normDate(r['วันที่สอบ']),start_time:normTime(r['เวลาเริ่ม'])||null,end_time:normTime(r['เวลาสิ้นสุด'])||null,subject_code:txt(r['รหัสวิชา'])||null,subject_name:txt(r['วิชา']),exam_type:txt(r['ประเภทการสอบ'])||null,room:txt(r['ห้องสอบ'])||null,note:txt(r['หมายเหตุ'])||null,semester:txt(r['ภาคเรียน'])||null,academic_year:txt(r['ปีการศึกษา'])||null,published:true})).filter(r=>r.class_level&&r.exam_date&&r.subject_name);if(!rows.length)return alert('ไม่พบแถวข้อมูลที่ถูกต้อง');if(!confirm(`นำเข้ากำหนดการสอบ ${rows.length} รายการ?`))return;if($('examReplace').checked)await deleteExistingGroups('student_exams',rows);for(const chunk of chunks(rows,400)){const {error}=await db.from('student_exams').insert(chunk);if(error)throw error}alert('นำเข้ากำหนดการสอบเรียบร้อย');await loadExams();renderDashboard()}catch(err){alert(err.message)}}

function renderGrades(){const q=$('gradeSearch').value.toLowerCase(),cl=$('gradeClassFilter').value;const rows=grades.filter(g=>{const s=g.students||{};return(!cl||s.class_level===cl)&&`${s.student_code||''} ${s.first_name||''} ${s.last_name||''}`.toLowerCase().includes(q)});$('gradeTable').innerHTML=rows.length?rows.map(g=>{const s=g.students||{};return `<tr class="border-t"><td class="p-3"><p class="font-bold">${esc([s.title,s.first_name,s.last_name].filter(Boolean).join(' '))}</p><p class="text-xs font-mono text-slate-400">${esc(s.student_code||'')}</p></td><td class="p-3">${esc(s.class_level||'')}</td><td class="p-3">${esc(g.academic_year)} / ${esc(g.semester)}</td><td class="p-3 max-w-[240px] truncate">${esc(g.original_file_name||'')}</td><td class="p-3">${new Date(g.uploaded_at).toLocaleDateString('th-TH')}</td><td class="p-3 text-right"><button onclick="openGradeFile('${g.id}')" class="px-3 py-1.5 rounded-lg bg-slate-900 text-white text-xs font-bold">เปิดไฟล์</button></td></tr>`}).join(''):'<tr><td colspan="6" class="p-8 text-center text-slate-400">ไม่พบไฟล์</td></tr>'}
window.openGradeFile=async id=>{const g=grades.find(x=>x.id===id);if(!g)return;const {data,error}=await db.storage.from(BUCKET).download(g.file_path);if(error)return alert(error.message);const url=URL.createObjectURL(data);window.open(url,'_blank');setTimeout(()=>URL.revokeObjectURL(url),120000)};

async function sheetRows(file,range=2){const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:false});const sh=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(sh,{defval:'',range,raw:true})}
function txt(v){return String(v??'').trim()}function numOrNull(v){const n=Number(v);return Number.isFinite(n)&&txt(v)!==''?n:null}
function normTime(v){if(v===null||v===undefined||v==='')return'';if(typeof v==='number'){const mins=Math.round((v%1)*24*60);return`${String(Math.floor(mins/60)%24).padStart(2,'0')}:${String(mins%60).padStart(2,'0')}`}const s=String(v).trim();const m=s.match(/(\d{1,2})[:.](\d{2})/);return m?`${m[1].padStart(2,'0')}:${m[2]}`:s.slice(0,5)}
function normDate(v){if(!v)return'';if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
async function deleteExistingGroups(table,rows){const keys=[...new Set(rows.map(r=>`${r.class_level}|${r.semester||''}|${r.academic_year||''}`))];for(const k of keys){const [cl,sem,yr]=k.split('|');let q=db.from(table).delete().eq('class_level',cl);if(sem)q=q.eq('semester',sem);else q=q.is('semester',null);if(yr)q=q.eq('academic_year',yr);else q=q.is('academic_year',null);const {error}=await q;if(error)throw error}}
function chunks(a,n){const o=[];for(let i=0;i<a.length;i+=n)o.push(a.slice(i,i+n));return o}
function downloadCsv(name,headers,rows){const lines=[headers.join(','),...rows.map(r=>headers.map(h=>`"${String(r[h]??'').replace(/"/g,'""')}"`).join(','))];const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
