(() => {
  const C=window.DonationCommon, db=C.db;
  const input=document.getElementById('nikorn-code'), status=document.getElementById('nikorn-status'), results=document.getElementById('nikorn-results');
  let lastCode=''; let pollTimer=null; let pollCount=0;
  function msg(text,ok=false){status.className=`mt-4 rounded-2xl p-4 text-sm border ${ok?'bg-emerald-50 text-emerald-700 border-emerald-200':'bg-rose-50 text-rose-700 border-rose-200'}`;status.textContent=text;status.classList.remove('hidden')}
  function stateMeta(v){return ({ready:['พร้อมดาวน์โหลด','bg-emerald-50 text-emerald-700 border-emerald-200','circle-check'],generating:['กำลังสร้างภาพ','bg-amber-50 text-amber-700 border-amber-200','loader-circle'],error:['สร้างภาพไม่สำเร็จ','bg-rose-50 text-rose-700 border-rose-200','circle-alert'],not_generated:['รอสร้างภาพ','bg-slate-50 text-slate-600 border-slate-200','clock-3']}[v]||['รอสร้างภาพ','bg-slate-50 text-slate-600 border-slate-200','clock-3'])}
  async function loadSettings(){try{const s=await C.loadDonationSettings();const img=document.getElementById('nikorn-example'),fb=document.getElementById('nikorn-example-fallback');if(s?.nikorn_enabled===false){msg('ขณะนี้โรงเรียนปิดระบบภาพ พม. นิกรชั่วคราว');document.getElementById('nikorn-search-form').classList.add('opacity-50','pointer-events-none')}const url=String(s?.nikorn_fallback_photo_url||'').trim();if(url){img.src=url;img.classList.remove('hidden');fb.classList.add('hidden');img.onerror=()=>{img.classList.add('hidden');fb.classList.remove('hidden')}}}catch(_){} }
  function render(rows){
    if(!rows.length){results.innerHTML='';return}
    results.innerHTML=rows.map(x=>{const m=stateMeta(x.nikorn_generation_status);const image=String(x.nikorn_image_url||'').trim();return `<article class="glass rounded-[2rem] overflow-hidden"><div class="grid lg:grid-cols-[.82fr_1.18fr]"><div class="relative min-h-[300px] bg-slate-950 flex items-center justify-center overflow-hidden">${image?`<img src="${C.escapeHtml(image)}" alt="ภาพ พม. นิกร ${C.escapeHtml(x.request_no)}" class="absolute inset-0 w-full h-full object-contain bg-slate-950">`:`<div class="text-center p-8"><div class="w-16 h-16 mx-auto rounded-2xl bg-white/10 text-orange-300 flex items-center justify-center"><i data-lucide="${m[2]}" class="w-8 h-8 ${x.nikorn_generation_status==='generating'?'animate-spin':''}"></i></div><p class="mt-4 text-white font-bold">${m[0]}</p><p class="mt-1 text-xs text-slate-400">${C.escapeHtml(x.request_no)}</p></div>`}</div><div class="p-6 sm:p-8"><div class="flex flex-wrap items-center gap-2"><span class="text-xs border px-2.5 py-1 rounded-full font-bold ${m[1]}">${m[0]}</span><span class="text-xs text-slate-400">${C.escapeHtml(x.request_no)}</span></div><h2 class="mt-4 text-2xl font-extrabold text-slate-900">${C.escapeHtml(x.display_name||'-')}</h2><div class="mt-4 grid sm:grid-cols-2 gap-3"><div class="rounded-2xl bg-orange-50 p-4"><p class="text-xs text-orange-600">จำนวนเงิน</p><p class="font-extrabold text-orange-800 mt-1">${C.formatTHB(x.amount)}</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="text-xs text-slate-500">วันที่ร่วมบุญ</p><p class="font-bold mt-1">${C.formatDateTH(x.transfer_date)}</p></div></div>${x.certificate_no?`<p class="mt-4 text-sm text-slate-500">เลขใบอนุโมทนาบัตร <b class="text-slate-800">${C.escapeHtml(x.certificate_no)}</b></p>`:''}<div class="mt-6 flex flex-wrap gap-3">${image?`<a href="${C.escapeHtml(image)}" target="_blank" rel="noopener" download class="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-orange-500 text-white font-extrabold"><i data-lucide="image-down" class="w-5 h-5"></i> เปิด / ดาวน์โหลดภาพ</a>`:''}${x.certificate_no?`<a href="../verify/?no=${encodeURIComponent(x.certificate_no)}" class="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-emerald-50 text-emerald-700 border border-emerald-100 font-bold"><i data-lucide="badge-check" class="w-5 h-5"></i> ตรวจสอบใบ</a>`:''}<button type="button" data-refresh class="inline-flex items-center gap-2 px-5 py-3 rounded-2xl bg-slate-100 text-slate-700 font-bold"><i data-lucide="refresh-cw" class="w-4 h-4"></i> ตรวจสถานะอีกครั้ง</button></div></div></div></article>`}).join('');
    document.querySelectorAll('[data-refresh]').forEach(b=>b.onclick=()=>search(lastCode,true));
    try{lucide.createIcons()}catch(_){}
  }
  async function search(code,silent=false){code=String(code||'').trim().toUpperCase();if(!code)return msg('กรุณากรอกรหัสประวัติผู้บริจาค');if(!db)return msg('ยังไม่ได้เชื่อมต่อ Supabase');lastCode=code;if(!silent){results.innerHTML='<div class="glass rounded-2xl p-7 text-center text-slate-500">กำลังตรวจสอบภาพ...</div>';status.classList.add('hidden')}
    try{let {data,error}=await db.rpc('get_donation_history_v2',{p_history_code:code});if(error){const legacy=await db.rpc('get_donation_history',{p_history_code:code});if(legacy.error)throw error;data=(legacy.data||[]).map(x=>({...x,nikorn_generation_status:'not_generated',nikorn_image_url:''}));}
      const rows=data||[];if(!rows.length){results.innerHTML='';return msg('ไม่พบรายการจากรหัสนี้ กรุณาตรวจสอบรหัสอีกครั้ง')}
      localStorage.setItem('wnw-donation-history-code',code);render(rows);msg(`พบ ${rows.length} รายการ`,true);
      const pending=rows.some(x=>['generating','not_generated'].includes(x.nikorn_generation_status));
      clearTimeout(pollTimer); if(pending && pollCount<6){pollCount++;pollTimer=setTimeout(()=>search(code,true),8000)} else pollCount=0;
    }catch(err){results.innerHTML='';msg('ตรวจสอบไม่สำเร็จ: '+(err.message||err))}
  }
  document.getElementById('nikorn-search-form').addEventListener('submit',e=>{e.preventDefault();pollCount=0;search(input.value)});
  const qs=new URLSearchParams(location.search);const saved=qs.get('code')||localStorage.getItem('wnw-donation-history-code')||'';if(saved){input.value=saved;search(saved)}
  C.loadBranding().then(C.applyBranding).catch(()=>{});loadSettings();try{lucide.createIcons()}catch(_){}
})();